name: squadron
description: Multithreading and worker thread pool for Dart / Flutter, to offload CPU-bound and heavy I/O tasks to Isolate or Web Worker threads.
version: 6.0.0
repository: https://github.com/d-markey/squadron

environment:
  sdk: ^3.0.0

dependencies:
  cancelation_token: ^1.1.0
  http: ^1.0.0
  meta: ^1.11.0
  logger: ^2.0.2

dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.0
  coverage: ^1.6.3
  js: ^0.7.0
  lints: ^3.0.0
  test: ^1.24.2

topics:
  - concurrency
  - isolate
  - multithread
  - web-worker

funding:
  - https://github.com/sponsors/d-markey
