name: squadron
description: Multithreading and worker thread pool in Dart to offload CPU-bound and heavy I/O tasks to Isolate or Web Worker threads.
version: 3.4.0
homepage: https://github.com/d-markey/squadron
repository: https://github.com/d-markey/squadron

environment:
  sdk: '>=2.13.0 <3.0.0'

#dependencies:

dev_dependencies:
  coverage: ^1.1.0
  lints: ^1.0.1
  test: ^1.20.2
  js: ^0.6.4
  build_runner: ^2.1.8
  build_web_compilers: ^3.2.2
  http: ^0.13.4
