name: squadron
description: Multithreading and worker pools in Dart to offload CPU-bound or long running tasks and give your mobile and Web apps some air.
version: 1.0.3
homepage: https://github.com/d-markey/squadron
repository: https://github.com/d-markey/squadron

environment:
  sdk: '>=2.14.0 <3.0.0'

#dependencies:

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
