name: squadron
description: Multithreading and worker pools in Dart to offload CPU-bound or long running tasks and give your mobile and Web apps some air.
version: 2.0.0
homepage: https://github.com/d-markey/squadron
repository: https://github.com/d-markey/squadron

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  js: ^0.6.3

dev_dependencies:
  lints: ^1.0.0
  test: ^1.18.2
  build_runner: ^2.1.4
  build_web_compilers: ^3.2.1
